- name: Configure Bash
  blockinfile:
    path: '~/.bashrc'
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      export PATH="$PATH:$HOME/.dev-env/bin"
      export PATH="$PATH:$HOME/.local/bin"

      export QUBO_PATH=~/qubo
      export GAZEBO_MODEL_PATH="$QUBO_PATH/src/qubo_gazebo/nbrf:$GAZEBO_MODEL_PATH"
      source "$QUBO_PATH/devel/setup.bash"

- name: Create directories
  file:
    path: '~/qubo/src'
    state: directory

- name: Ensure ssh directory exists
  file:
    path: ~/.ssh
    state: directory

- name: Configure SSH client
  ansible.builtin.blockinfile:
    path: ~/.ssh/config
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      # Share auth between SSH sessions. Don't have to authenticate again if you already have an open session.
      Host *
          ControlMaster auto
          ControlPersist 1
          ControlPath ~/.ssh/ssh_mux_%h_%p_%r

      Host gitlab.com
          HostName gitlab.com
          IdentityFile {{ ssh_keypair_path }}

# Primarily an Ubuntu 18.04 issue. May be fixed in later versions of Ubuntu.
# So test without this on an upgrade, as we'd rather avoid messing with the default configuration.
- name: Configure network interface
  become: yes
  ansible.builtin.copy:
    src: "{{ role_path }}/files/01-netcfg.yaml"
    dest: /etc/netplan/01-netcfg.yaml
    force: yes
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: Apply netplan configuration
