# Include variables that depend on the system architecture (e.g. x86_64 vs arm64).
- include_vars: "{{ role_path }}/vars/{{ ansible_facts['machine'] }}.yaml"

- name: Add user to necessary groups for accessing serial ports
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    append: yes
    groups: dialout

- name: Install R@M embedded packages
  become: yes
  apt:
    update_cache: yes
    name:
      - screen
      - gdb
      - openocd
      - lm4flash
      - astyle

- name: Install Arm GNU Toolchain
  block:
    - name: Ensure build directory exists
      ansible.builtin.file:
        path: "{{ role_path }}/build"
        state: directory
    - name: Download and verify Arm GNU Toolchain
      ansible.builtin.get_url:
        url: "{{ arm_gnu_toolchain_url }}"
        # Important to specify a destination so we don't download the file again if it's already there.
        dest: "{{ role_path }}/build/{{ arm_toolchain_archive_name }}"
        checksum: "{{ arm_gnu_toolchain_checksum }}"
    - name: Ensure '~/.local/' directory exists.
      ansible.builtin.file:
        path: ~/.local
        state: directory
    # Extract directly to our desired destination directory.
    # The files are pretty big so we don't want to just copy them.
    # The directory structure matches, so this is fine.
    # The only problem is that the archive puts everything under a single directory, which is generally a good thing.
    # So, we have to use GNU tar's transform option to turn this into a tarbomb.
    # There might be a cleaner way to do this while maintaining Ansible's idempotency and avoiding unnecessary copies of large files.
    # Perhaps a `cp -al` to hardlink to the desired location, or symlinks if they work.
    #
    # If you plan on "fixing" this, it's probably better to just use a package manager.
    # Either update the Ubuntu version (requires updating ROS version, rewriting a lot of code), or use a separate package manager such as Nix or Homebrew.
    - name: Extract Arm GNU Toolchain archive
      ansible.builtin.unarchive:
        src: "{{ role_path }}/build/{{ arm_toolchain_archive_name }}"
        dest: ~/.local/
        extra_opts:
          - --transform
          - "s/^{{ arm_toolchain_extracted_dirname }}//"
