# Include variables that depend on the system architecture (e.g. x86_64 vs arm64).
- include_vars: "{{ role_path }}/vars/{{ ansible_facts['machine'] }}.yaml"

- name: Add user to necessary groups for accessing serial ports
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    append: yes
    groups: dialout

- name: Install R@M embedded packages
  become: yes
  apt:
    update_cache: yes
    name:
      - screen
      - openocd
      - lm4flash
      - astyle # code auto-formatter

- name: Install Arm GNU Toolchain
  block:
    - name: Ensure build directory exists
      ansible.builtin.file:
        path: "{{ role_path }}/build"
        state: directory
    - name: Download and verify Arm GNU Toolchain
      ansible.builtin.get_url:
        url: arm_gnu_toolchain_url
        dest: "{{ role_path }}/build/"
        checksum: arm_gnu_toolchain_checksum
      register: arm_toolchain
    - name: Install
      # TODO Either `/opt/`, maybe `/usr/local/`, or user `~/.local/`
      # TODO Use arm_toolchain.dest
    - name: Debug
      debug:
        msg: "Toolchain file path: {{ arm_toolchain.dest }}"
