# Miscellaneous packages.
# e.g. various text editors and useful utilities people may want to use.

- name: Install miscellaneous packages
  become: yes
  apt:
    name:
      - vim
      - neovim
      - emacs
      - nano
      - magic-wormhole
      - rlwrap
      - pdfgrep
      - git-annex
      - git-lfs
      - trash-cli
      - extundelete
      - shellcheck
      - valgrind
      - gdb
      - lldb
      - clang
      - tmux
      - screen
      - byobu
      - tree
