- name: Add ROS's APT repo key
  become: yes
  ansible.builtin.apt_key:
    url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc
    id: C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654

- name: Add ROS's APT repository
  become: yes
  ansible.builtin.apt_repository:
    repo: deb http://packages.ros.org/ros/ubuntu bionic main

- name: Update apt cache
  become: yes
  apt:
    update_cache: yes

# The next few are large installs, so do them one at a time so have a better feeling for current progress.

- name: Install ros-melodic-desktop-full
  become: yes
  apt:
    name:
      - ros-melodic-desktop-full

- name: Install ros-melodic-uuv-simulator
  become: yes
  apt:
    name:
      - ros-melodic-uuv-simulator

- name: Install python3-catkin-tools
  become: yes
  apt:
    name:
      - python3-catkin-tools

- name: Install other packages
  become: yes
  apt:
    name:
      - python2.7
      - python-pip
      - mesa-utils
      - python-pygame

- name: Install Python packages
  pip:
    executable: pip2
    name:
      - rospkg
