- name: Ensure ssh directory exists
  file:
    path: ~/.ssh
    state: directory

- name: Generate an SSH keypair for authenticating with Git remote
  community.crypto.openssh_keypair:
    path: ~/.ssh/id-ram_ed25519
    type: ed25519
