- name: Run playbook
  hosts: local
  vars:
    ssh_keypair_path: '~/.ssh/id-ram_ed25519'
  roles:
    - role: base
      tags: [ base ]
    - role: core
    - role: postinstall
      tags: [ postinstall ]
