# - name: Prompt
#   hosts: all
#   vars_prompt:
#     - name: username
#       prompt: What is your username?
#       default: "ram"
#       private: no

# - name: Debug output
#   ansible.builtin.debug:
#     msg: "Hello"

- name: Run playbook
  hosts: local
  roles:
    - role: init
    - role: embedded
    - role: software
